name: flutter_application_1
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  flutter_localizations:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  wakelock_plus: ^1.0.0
  intl: ^0.19.0 
  flutter_secure_storage: ^8.0.0 
  provider: ^6.1.2
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/splash/
    - assets/images/icons/
    - assets/images/default_image_url.png
    - assets/images/categories/
    - assets/images/banner/
